/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "bg-base": "#050505",
        "surface-1": "#0D0D0D",
        "surface-2": "#141414",
        "surface-3": "#1E1E1E",
        "surface": "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-variant": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "border-hairline": "rgba(255, 255, 255, 0.08)",
        "text-primary": "#FFFFFF",
        "text-secondary": "rgba(255, 255, 255, 0.60)",
        "text-disabled": "rgba(255, 255, 255, 0.30)",
        
        "primary": "#c3f5ff",
        "primary-container": "#00e5ff",
        "primary-fixed": "#9cf0ff",
        "primary-fixed-dim": "#00daf3",
        "on-primary": "#00363d",
        "on-primary-container": "#00626e",
        "on-primary-fixed": "#001f24",
        "on-primary-fixed-variant": "#004f58",
        
        "secondary": "#C77DFF",
        "secondary-container": "#691a9f",
        "secondary-fixed": "#f2daff",
        "secondary-fixed-dim": "#e1b6ff",
        "on-secondary": "#4c007b",
        "on-secondary-container": "#d69eff",
        "on-secondary-fixed": "#2e004d",
        "on-secondary-fixed-variant": "#691a9f",
        
        "tertiary": "#ffe7e6",
        "tertiary-container": "#ffc1c0",
        "tertiary-fixed": "#ffdad9",
        "tertiary-fixed-dim": "#ffb3b2",
        "on-tertiary": "#680013",
        "on-tertiary-container": "#b4012a",
        "on-tertiary-fixed": "#410008",
        "on-tertiary-fixed-variant": "#920020",
        
        "error": "#FF4757",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        
        "outline": "#849396",
        "outline-variant": "#3b494c",
        "surface-tint": "#00daf3",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#bac9cc",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#006875",
        "background": "#131313",
        "on-background": "#e5e2e1",
        
        "glow-cyan": "rgba(0, 229, 255, 0.35)",
        "glow-fuchsia": "rgba(199, 125, 255, 0.30)",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1rem",
        "margin": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "PingFang SC", "MiSans", "Microsoft YaHei", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Inter", "PingFang SC", "sans-serif"],
        "headline-lg": ["Inter", "PingFang SC", "sans-serif"],
        "headline-md": ["Inter", "PingFang SC", "sans-serif"],
        "body-lg": ["Inter", "PingFang SC", "sans-serif"],
        "body-md": ["Inter", "PingFang SC", "sans-serif"],
        "body-sm": ["Inter", "PingFang SC", "sans-serif"],
        "label-md": ["Inter", "PingFang SC", "sans-serif"],
        "label-sm": ["Inter", "PingFang SC", "sans-serif"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "code-md": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      boxShadow: {
        "neon-cyan": "0 0 24px rgba(0, 229, 255, 0.35)",
        "neon-cyan-sm": "0 0 12px rgba(0, 229, 255, 0.5)",
        "neon-cyan-lg": "0 0 32px rgba(0, 229, 255, 0.5)",
        "neon-fuchsia": "0 0 16px rgba(199, 125, 255, 0.30)",
        "neon-fuchsia-sm": "0 0 10px rgba(199, 125, 255, 0.4)",
      }
    },
  },
  plugins: [],
};
